<a href="https://colab.research.google.com/github/sachinkun21/Tensorflow/blob/master/Tensorflow_2_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow-2.0 in Action 


![title](img/tensorflow1.png)

> TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.

> Indented block


> Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

## Why Tensorflow?

![title](img/comparision.png)

![title](img/comparision2.png)

## Installation of Tensorflow

>TensorFlow is tested and supported on the following 64-bit systems:

>1.Ubuntu 16.04 or later

>2.Windows 7 or later

>3.macOS 10.12.6 (Sierra) or later (no GPU support)

>4.Raspbian 9.0 or later

> **pip install tensorflow==2.0.0**

> To run from Anaconda Prompt

> **!pip install tensorflow==2.0.0**

> To run from Jupyter Notebook

`Both Tensorflow 2.0 and Keras have been released for four years (Keras was released in March 2015, and Tensorflow was released in November of the same year). The rapid development of deep learning in the past days, we also know some problems of Tensorflow1.x and Keras:`

* Using Tensorflow means programming static graphs, which is difficult and inconvenient for programs that are familiar with imperative programming

* Tensorflow api is powerful and flexible, but it is more complex, confusing and difficult to use.

* Keras api is productive and easy to use, but lacks flexibility for research


#### Version Check

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.2.0
Keras version: 2.3.0-tf


`Tensorflow2.0 is a combination design of Tensorflow1.x and Keras. Considering user feedback and framework development over the past four years, it largely solves the above problems and will become the future machine learning platform.`

> Tensorflow 2.0 is built on the following core ideas:


* The coding is more pythonic, so that users can get the results immediately like they are programming in numpy
* Retaining the characteristics of static graphs (for performance, distributed, and production deployment), this makes TensorFlow fast, scalable, and ready for production.
* Using Keras as a high-level API for deep learning, making Tensorflow easy to use and efficient
* Make the entire framework both high-level features (easy to use, efficient, and not flexible) and low-level features (powerful and scalable, not easy to use, but very flexible)

>Eager execution is by default in TensorFlow 2.0 and, it needs no special setup.
>The following below code can be used to find out whether a CPU or GPU is in use

### GPU/CPU Check

In [0]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


### Tensor Constant

In [0]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=42>

In [0]:
ineuron.numpy()

42

In [0]:
ineuron1 = tf.constant(1, dtype = tf.int64)
ineuron1

<tf.Tensor: id=22, shape=(), dtype=int64, numpy=1>

In [0]:
ineuron_x = tf.constant([[4,2],[9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [0]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]])

In [0]:
print('shape:',ineuron_x.shape)
print(ineuron_x.dtype)

shape: (2, 2)
<dtype: 'int32'>


#### Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [0]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [0]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [0]:
import tensorflow as tf
const2 = tf.constant([[3,4,5], [3,4,5]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


>We have defined two constants and we add one value to the other. 
>As a result, we got a Tensor object with the result of the adding. 

#### Random constant

In [0]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: id=38, shape=(2, 2), dtype=float32, numpy=
array([[ 0.79373837,  1.3887426 ],
       [-0.58256006, -1.5399069 ]], dtype=float32)>

In [0]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: id=42, shape=(2, 2), dtype=int32, numpy=
array([[1, 8],
       [4, 5]])>

### Variables

>A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

#### Declaring variables

In [0]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

>TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

#### The datatype can be explicitly specified

In [0]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

`TensorFlow has a large number of built-in datatypes.`
* tf.float16: 16-bit half-precision floating-point.
* tf.float32: 32-bit single-precision floating-point.
* tf.float64: 64-bit double-precision floating-point.
* tf.bfloat16: 16-bit truncated floating-point.
* tf.complex64: 64-bit single-precision complex.
* tf.complex128: 128-bit double-precision complex.
* tf.int8: 8-bit signed integer.
* tf.uint8: 8-bit unsigned integer.
* tf.uint16: 16-bit unsigned integer.
* tf.uint32: 32-bit unsigned integer.
* tf.uint64: 64-bit unsigned integer.
* tf.int16: 16-bit signed integer.
* tf.int32: 32-bit signed integer.
* tf.int64: 64-bit signed integer.
* tf.bool: Boolean.
* tf.string: String.
* tf.qint8: Quantized 8-bit signed integer.
* tf.quint8: Quantized 8-bit unsigned integer.
* tf.qint16: Quantized 16-bit signed integer.
* tf.quint16: Quantized 16-bit unsigned integer.
* tf.qint32: Quantized 32-bit signed integer.
* tf.resource: Handle to a mutable resource.
* tf.variant: Values of arbitrary types.


#### To reassign a variable, use var.assign()

In [0]:
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [0]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [0]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.7069958 , -0.02613977],
       [-0.6598021 , -1.0498033 ]], dtype=float32)>


>We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [0]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [0]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

#### Shaping a tensor

In [0]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


#### Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [0]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: id=210, shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [0]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: id=213, shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

### Rank of a tensor

>The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [0]:
tf.rank(tensor)

<tf.Tensor: id=215, shape=(), dtype=int32, numpy=3>

>(the shape is () because the output here is a scalar value)

#### Specifying an element of a tensor

In [0]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: id=220, shape=(), dtype=float32, numpy=18.0>

#### Casting a tensor to a NumPy variable

In [0]:
print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [0]:
print(tensor[1, 0, 2].numpy())

18.0


#### Finding the size or length of a tensor

In [0]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [0]:
#the datatype of a tensor
tensor3.dtype

tf.float32

### Tensorflow mathematical operations
>Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.


In [0]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-1.2265512  -1.4969218 ]
 [ 0.01587692  0.5437373 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.90549344  0.50011796]
 [ 1.4741822  -0.03823759]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.1320446 -0.9968038]
 [ 1.4900591  0.5054997]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4.545614   0.99361783]
 [2.220276   0.25552997]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.11859457 0.36905712]
 [4.4373584  1.6578138 ]], shape=(2, 2), dtype=float32)


### Performing element-wise primitive tensor operations

In [0]:
tensor*tensor

<tf.Tensor: id=246, shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

### Broadcasting in Tensorflow

>Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

>The simplest example is multiplication of  a tensor by a scalar value.

In [0]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


### Transpose Matrix multiplication

In [0]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: id=254, shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [0]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: id=255, shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])>

##### Casting with truncation

In [0]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: id=257, shape=(), dtype=int32, numpy=4>

###  Ragged tensors

`A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.`

#### Below example shows how to declare a constant ragged array

In [0]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


### Squared difference of tensors

In [0]:
varx = [4,5,6,1,2]
vary = 8
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

#### Calculate the mean

>Function available
>tf.reduce_mean().

`Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type`

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [0]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])

#### Calculate the mean across all axes

In [0]:
tf.reduce_mean(input_tensor=numbers) #default axis = None

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

#### Calculate the mean across columns (reduce rows) with this:

In [0]:
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

#### When keepdims = True

In [0]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

#### Calculate the mean across rows (reduce columns) with this:

In [0]:
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

#### When keepdims= True

In [0]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

####  Random values generation

##### tf.random.normal()

>tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

>The function is as follows:
    
`tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [0]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
randon_num = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(randon_num)

tf.Tensor(
[[11.926843 11.951866]
 [11.554054  8.495991]
 [11.13671  11.879669]], shape=(3, 2), dtype=float32)


####  tf.random.uniform()

>The function is this:
    
>tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

`This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't.

Example:`

In [0]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.24019718, 0.6144402 , 0.6651863 , 0.4577496 ],
       [0.95334494, 0.8498589 , 0.86562073, 0.8837615 ]], dtype=float32)>

#### Setting the seed

In [0]:
tf.random.set_seed(11)
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 1
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [0]:
tf.random.set_seed(11) #same seed
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 2
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Practical example of Random values using Dices

In [0]:
dice11 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

# lets ADD
dice_sum1 = dice11 + dice12
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

tf.Tensor(
[[ 2  2  4]
 [ 1  6  7]
 [ 6  1  7]
 [ 6  6 12]
 [ 4  4  8]
 [ 6  2  8]
 [ 5  6 11]
 [ 5  5 10]
 [ 4  6 10]
 [ 6  6 12]], shape=(10, 3), dtype=int32)


#### Finding the indices of the largest and smallest element

>The following functions are available:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [0]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)


i = tf.argmax(input=tensor_1d)
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())


i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',tensor_1d[i].numpy())

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)
index of max;  tf.Tensor(2, shape=(), dtype=int64)
Max element:  51
index of min:  7
Min element:  -19


#### Saving and restoring using a checkpoint

In [0]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


#### Using tf.function

`tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.`


>Its function is as follows:
    
`tf.function(
func=None,input_signature=None,autograph=True,experimental_autograph_options=None
)`


In [0]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

## Calculate the gradient

### GradientTape

>Another difference from numpy is that it can automatically track the gradient of any variable.

>Open one GradientTape and `tape.watch()` track variables through

In [0]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47931308 -0.9943058 ]
 [ 0.9353223   0.80492437]], shape=(2, 2), dtype=float32)


>For all variables, the calculation is tracked by default and used to find the gradient, so do not `usetape.watch()`

In [0]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47931308 -0.9943058 ]
 [ 0.9353223   0.80492437]], shape=(2, 2), dtype=float32)


> You can GradientTapefind higher-order derivatives by opening a few more:

In [0]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.5205455  0.00913197]
 [0.23476017 0.47745854]], shape=(2, 2), dtype=float32)


# Keras, a High-Level API for TensorFlow 2

![title](img/keras.png)

## The Keras Sequential model

`To build a Keras Sequential model, you add layers to it in the same order that you want the computations to be undertaken by the network.`

`After you have built your model, you compile it; this optimizes the computations that are to be undertaken, and is where you allocate the optimizer and the loss function you want your model to use.`

`The next stage is to fit the model to the data. This is commonly known as training the model, and is where all the computations take place. It is possible to present the data to the model either in batches, or all at once.`

`Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having trained your model, you can use it to make predictions on new data. So, the workflow is: build, compile, fit, evaluate, make predictions.`

`There are two ways to create a Sequential model. Let's take a look at each of them.`

![title](img/kerasmodelling.png)

### Using Sequential model

`Firstly, you can pass a list of layer instances to the constructor, as in the following example.For now, we will just explain enough to allow you to understand what is happening here.`

`Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8-bit integer (uint8), as are the labels:`

#### Loading the datset

In [0]:
mnist_data = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist_data.load_data()

11493376/11490434 [==============================] - 14s 1us/step


#### Definning the variables

In [0]:
epochs=10
batch_size = 32

In [0]:
# normalize all the data points and cast the labels to int64
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

#### Building the Architecture 

In [0]:
mnistmodel1 = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])


#### Compiling the model

In [0]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

#### Fitting the model

In [0]:
mnistmodel1.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 12s 205us/sample - loss: 0.2185 - accuracy: 0.9348
Epoch 2/5
60000/60000 [==============================] - 13s 208us/sample - loss: 0.0986 - accuracy: 0.9701
Epoch 3/5
60000/60000 [==============================] - 12s 193us/sample - loss: 0.0689 - accuracy: 0.9789
Epoch 4/5
60000/60000 [==============================] - 12s 193us/sample - loss: 0.0536 - accuracy: 0.9825
Epoch 5/5
60000/60000 [==============================] - 12s 199us/sample - loss: 0.0439 - accuracy: 0.9858


#### Evaluate the mnistmodel1

In [0]:
mnistmodel1.evaluate(test_x, test_y)

10000/10000 [==============================] - 1s 108us/sample - loss: 0.0751 - accuracy: 0.9771


[0.07506247069942765, 0.9771]

>This represents a loss of 0.09 and an accuracy of 0.9801 on the test data. 

>An accuracy of 0.98 means that out of 100 test data points, 98 were, on average, correctly identified by the model.

In [0]:
The second way to create a Sequential model
The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:



#### Building the Architecture & Compiling

In [0]:
mnistmodel2 = tf.keras.models.Sequential();
mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
mnistmodel2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

#### Fitting the mnistmodel2

In [0]:
mnistmodel2.fit(train_x, train_y, batch_size=64, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 105us/sample - loss: 0.2445 - accuracy: 0.9281
Epoch 2/5
60000/60000 [==============================] - ETA: 0s - loss: 0.1054 - accuracy: 0.96 - 6s 96us/sample - loss: 0.1054 - accuracy: 0.9682
Epoch 3/5
60000/60000 [==============================] - 6s 105us/sample - loss: 0.0741 - accuracy: 0.9773
Epoch 4/5
60000/60000 [==============================] - 5s 86us/sample - loss: 0.0555 - accuracy: 0.9819
Epoch 5/5
60000/60000 [==============================] - 6s 92us/sample - loss: 0.0440 - accuracy: 0.9861


#### Evaluate the mnistmodel2

In [0]:
mnistmodel2.evaluate(test_x, test_y)

10000/10000 [==============================] - 1s 90us/sample - loss: 0.0637 - accuracy: 0.9810


[0.06365259396769106, 0.981]

![title](img/kerasmodelling2.png)

### Keras functional API

`The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. It also supports more advanced models. These models include multi-input and multi-output models, models with shared layers, and models with residual connections.`

In [0]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10


#### Building the Architecture

In [0]:
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

#### Compile & Fit

In [0]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

#### Evaluate the mnistmodel3

In [0]:
mnistmodel3.evaluate(test_x, test_y)

### Subclassing the Keras Model class

In [0]:
import tensorflow as tf

#### Building the subclass architecture

In [0]:
class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [0]:
mnistmodel4 = MNISTModel()

#### Compile & Fit

In [0]:
batch_size = 32
steps_per_epoch = len(train_x.numpy())//batch_size
print(steps_per_epoch)
mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

1875
Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 199us/sample - loss: 0.2182 - accuracy: 0.9355
Epoch 2/10
60000/60000 [==============================] - 12s 201us/sample - loss: 0.0961 - accuracy: 0.9709
Epoch 3/10
60000/60000 [==============================] - 12s 194us/sample - loss: 0.0697 - accuracy: 0.9783
Epoch 4/10
60000/60000 [==============================] - 12s 205us/sample - loss: 0.0536 - accuracy: 0.9826
Epoch 5/10
60000/60000 [==============================] - 12s 193us/sample - loss: 0.0424 - accuracy: 0.9861
Epoch 6/10
60000/60000 [==============================] - 12s 195us/sample - loss: 0.0363 - accuracy: 0.9878
Epoch 7/10
60000/60000 [==============================] - 11s 190us/sample - loss: 0.0304 - accuracy: 0.9890
Epoch 8/10
60000/60000 [==============================] - 12s 199us/sample - loss: 0.0276 - accuracy: 0.9906
Epoch 9/10
60000/60000 [==============================] - 12s 196us/sample - loss: 0.0244 - accuracy

[0.06979138339359196, 0.9837]

#### Evaluate the mnistmodel4

In [0]:
mnistmodel4.evaluate(test_x, test_y)